#1.1.9 Art
import turtle as trtl
#draw base of the house
trtl.penup()
trtl.goto(-250, -300)
trtl.pendown()
trtl.pensize(2)
trtl.color("black")
trtl.fillcolor("lavenderblush")
trtl.begin_fill()
trtl.forward(500)
trtl.left(90)
trtl.forward(500)
trtl.left(90)
trtl.forward(500)
trtl.left(90)
trtl.forward(500)
trtl.end_fill()


#draw roof of the house
trtl.penup()
trtl.goto(-250, 200)
trtl.pendown()
trtl.color("black")
trtl.fillcolor("pink")
trtl.begin_fill()
trtl.goto(0, 350)
trtl.goto(250, 200)
trtl.goto(-250, 200)
trtl.end_fill()


#stripes of the house
n=10
for n in range(10):
  trtl.penup()
  trtl.goto(-250+50*n, 200)
  trtl.pendown()
  trtl.pensize(1)
  trtl.color("black")
  trtl.fillcolor("pink")
  trtl.begin_fill()
  trtl.forward(500)
  trtl.left(90)
  trtl.forward(20)
  trtl.left(90)
  trtl.forward(500)
  trtl.left(90)
  trtl.forward(20)
  trtl.end_fill()
  trtl.setheading(270)

  
#draw door of the house
trtl.penup()
trtl.goto(-225, -25)
trtl.pendown()
trtl.pensize(2)
trtl.color("black")
trtl.fillcolor("linen")
trtl.begin_fill()
trtl.forward(270)
trtl.left(90)
trtl.forward(150)
trtl.left(90)
trtl.forward(270)
trtl.left(90)
trtl.forward(150)
trtl.end_fill()
trtl.setheading(270)

#draw doorknob of the house
trtl.penup()
trtl.goto(-100,-190)
trtl.pendown()
trtl.color("black")
trtl.fillcolor("tan")
trtl.begin_fill()
trtl.circle(10)
trtl.end_fill()


#draw window of the house
trtl.penup()
trtl.goto(-65,100)
trtl.pendown()
trtl.pensize(2)
trtl.color("black")
trtl.fillcolor("azure")
trtl.begin_fill()
trtl.forward(300)
trtl.left(90)
trtl.forward(300)
trtl.left(90)
trtl.forward(300)
trtl.left(90)
trtl.forward(300)
trtl.end_fill()
trtl.setheading(270)

#draw table in the window of the house
trtl.setheading(180)
trtl.penup()
trtl.goto(235,-160)
trtl.pendown()
trtl.pensize(2)
trtl.color("black")
trtl.fillcolor("linen")
trtl.begin_fill()
trtl.forward(300)
trtl.left(90)
trtl.forward(50)
trtl.left(90)
trtl.forward(300)
trtl.left(90)
trtl.forward(50)
trtl.end_fill()
trtl.setheading(270)

#draw flower pot in the window of the house
trtl.penup()
trtl.goto(-50,-150)
trtl.pendown()
trtl.pensize(2)
trtl.color("black")
trtl.fillcolor("lavender")
trtl.begin_fill()
trtl.forward(50)
trtl.left(90)
trtl.forward(50)
trtl.left(90)
trtl.forward(50)
trtl.left(90)
trtl.forward(50)
trtl.end_fill()
trtl.setheading(270)

#draw flower in the flower pot
trtl.penup()
trtl.goto(-25,-110)
trtl.pencolor("green")
trtl.pendown()
trtl.setheading(270)
trtl.forward(40)
trtl.pensize(1)
trtl.shape("circle")
trtl.penup()
trtl.goto(-25,-110)
trtl.pendown()  
for petal in range(6):
  trtl.right(60)
  trtl.forward(15)
  trtl.color("mediumorchid")
  rem = petal % 2
  if rem == 0:
    trtl.fillcolor("purple")
  trtl.stamp()
  trtl.goto(-25,-110)
for petal in range(1):
  trtl.penup()
  trtl.goto(-25,-80)
  trtl.pendown()
  trtl.right(360)
  trtl.forward(30)
  trtl.color("lightyellow")
  trtl.stamp()

#draw flower pot in the window of the house
trtl.penup()
trtl.goto(30,-150)
trtl.pendown()
trtl.pensize(2)
trtl.color("black")
trtl.fillcolor("mintcream")
trtl.begin_fill()
trtl.forward(50)
trtl.left(90)
trtl.forward(50)
trtl.left(90)
trtl.forward(50)
trtl.left(90)
trtl.forward(50)
trtl.end_fill()
trtl.setheading(270)

#draw flower in the flower pot
trtl.penup()
trtl.goto(50,-110)
trtl.pencolor("olivedrab")
trtl.pendown()
trtl.setheading(270)
trtl.forward(40)
trtl.pensize(1)
trtl.shape("circle")
trtl.penup()
trtl.goto(50,-110)
trtl.pendown()  
for petal in range(6):
  trtl.right(60)
  trtl.forward(15)
  trtl.color("mediumslateblue")
  rem = petal % 2
  if rem == 0:
    trtl.fillcolor("plum")
  trtl.stamp()
  trtl.goto(50,-110)
for petal in range(1):
  trtl.penup()
  trtl.goto(50,-80)
  trtl.pendown()
  trtl.right(360)
  trtl.forward(30)
  trtl.color("lightyellow")
  trtl.stamp()

#draw flower pot in the window of the house
trtl.penup()
trtl.goto(150,-150)
trtl.pendown()
trtl.pensize(2)
trtl.color("black")
trtl.fillcolor("lightcyan")
trtl.begin_fill()
trtl.forward(50)
trtl.left(90)
trtl.forward(50)
trtl.left(90)
trtl.forward(50)
trtl.left(90)
trtl.forward(50)
trtl.end_fill()
trtl.setheading(270)

#draw flower in the flower pot
trtl.penup()
trtl.goto(170,-110)
trtl.pencolor("green")
trtl.pendown()
trtl.setheading(270)
trtl.forward(40)
trtl.pensize(1)
trtl.shape("circle")
trtl.penup()
trtl.goto(170,-110)
trtl.pendown()  
for petal in range(6):
  trtl.right(60)
  trtl.forward(15)
  trtl.color("palevioletred")
  rem = petal % 2
  if rem == 0:
    trtl.fillcolor("magenta")
  trtl.stamp()
  trtl.goto(170,-110)
for petal in range(1):
  trtl.penup()
  trtl.goto(170,-80)
  trtl.pendown()
  trtl.right(360)
  trtl.forward(30)
  trtl.color("lightyellow")
  trtl.stamp()
  

wn = trtl.Screen()
wn.mainloop()
