#1.1.9 Art
import turtle as trtl
#draw base of the house
trtl.penup()
trtl.goto(-250, -300)
trtl.pendown()
trtl.pensize(2)
trtl.color("black")
trtl.fillcolor("lavenderblush")
trtl.begin_fill()
trtl.forward(500)
trtl.left(90)
trtl.forward(500)
trtl.left(90)
trtl.forward(500)
trtl.left(90)
trtl.forward(500)
trtl.end_fill()

#draw roof of the house
trtl.penup()
trtl.goto(-250, 200)
trtl.pendown()
trtl.color("black")
trtl.fillcolor("plum")
trtl.begin_fill()
trtl.goto(0, 350)
trtl.goto(250, 200)
trtl.goto(-250, 200)
trtl.end_fill()


#stripes of the house
n=10
for n in range(10):
  trtl.penup()
  trtl.goto(-250+50*n, 200)
  trtl.pendown()
  trtl.pensize(1)
  trtl.color("black")
  trtl.fillcolor("pink")
  trtl.begin_fill()
  trtl.forward(500)
  trtl.left(90)
  trtl.forward(20)
  trtl.left(90)
  trtl.forward(500)
  trtl.left(90)
  trtl.forward(20)
  trtl.end_fill()
  trtl.setheading(270)

  
#draw door of the house
trtl.penup()
trtl.goto(-225, -25)
trtl.pendown()
trtl.pensize(2)
trtl.color("black")
trtl.fillcolor("azure")
trtl.begin_fill()
trtl.forward(270)
trtl.left(90)
trtl.forward(150)
trtl.left(90)
trtl.forward(270)
trtl.left(90)
trtl.forward(150)
trtl.end_fill()
trtl.setheading(270)

#draw window of the house
trtl.penup()
trtl.goto(-65,100)
trtl.pendown()
trtl.pensize(2)
trtl.color("black")
trtl.fillcolor("azure")
trtl.begin_fill()
trtl.forward(300)
trtl.left(90)
trtl.forward(300)
trtl.left(90)
trtl.forward(300)
trtl.left(90)
trtl.forward(300)
trtl.end_fill()
trtl.setheading(270)

#draw table in the window of the house
trtl.setheading(90)
trtl.penup()
trtl.goto(-65,20)
trtl.pendown()
trtl.pensize(2)
trtl.color("black")
trtl.fillcolor("linen")
trtl.begin_fill()
trtl.forward(200)
trtl.left(90)
trtl.forward(100)
trtl.left(90)
trtl.forward(200)
trtl.left(90)
trtl.forward(100)
trtl.end_fill()
trtl.setheading(270)

wn = trtl.Screen()
wn.mainloop()
